import assert from "node:assert/strict";
import {readdir,readFile} from "node:fs/promises";
import test from "node:test";
const topicsDir=new URL("../../../artifacts/publication/topics/",import.meta.url);
const topicFileName="personal-data-rights.json";
const topic=JSON.parse(await readFile(new URL(topicFileName,topicsDir),"utf8"));
async function otherContentIds(){const ids=new Set();for(const f of await readdir(topicsDir)){if(!f.endsWith(".json")||f===topicFileName)continue;const v=JSON.parse(await readFile(new URL(f,topicsDir),"utf8"));for(const e of v.content_entries??[])ids.add(e.content_id)}return ids}

test("개인정보 권리축은 10개 문답의 근거·규칙·분기를 닫는다",()=>{assert.equal(topic.topic_id,"hub.personal-data-rights");assert.equal(topic.sources.length,14);assert.equal(topic.rule_cards.length,10);assert.equal(topic.scenario_branches.length,10);assert.equal(topic.content_entries.length,10);const C=new Set(topic.sources.map(x=>x.coordinate_id)),R=new Set(topic.rule_cards.map(x=>x.rule_id)),S=new Set(topic.scenario_branches.map(x=>x.scenario_id)),E=new Set(topic.content_entries.map(x=>x.content_id));const used=new Set();for(const x of [...topic.rule_cards,...topic.scenario_branches,...topic.content_entries])for(const c of x.source_coordinate_ids){assert.ok(C.has(c));used.add(c)}assert.deepEqual(used,C);for(const e of topic.content_entries){assert.ok(e.rule_ids.every(x=>R.has(x)));assert.ok(e.scenario_ids.every(x=>S.has(x)));assert.deepEqual(e.hub_ids,[topic.topic_id]);assert.ok(e.audience_situation_ko.length>=25);assert.ok(e.action_steps_ko.length>=4);assert.ok(e.facts_to_check_ko.length>=5)}assert.deepEqual(new Set(topic.topic_hubs[0].content_ids),E)});

test("동의·최소수집·외부전달의 오해를 구별한다",()=>{const m=new Map(topic.content_entries.map(x=>[x.content_id,x]));assert.match(m.get("content.personal-data-rights-consent-is-not-only-lawful-basis").one_line_answer_ko,/동의 외에도.*법률상 의무.*계약 이행.*정당한 이익/);assert.match(m.get("content.personal-data-rights-minimum-necessary-and-optional-data").one_line_answer_ko,/선택정보.*거절해서는 안 되며.*입증/);assert.match(m.get("content.personal-data-rights-third-party-provision-vs-outsourcing").one_line_answer_ko,/제3자 제공.*독자 목적.*위탁.*업무 목적/);assert.match(m.get("content.personal-data-rights-notice-of-data-source").one_line_answer_ko,/출처.*처리 목적.*처리정지.*동의 철회/)});

test("유출 뒤 권리행사 순서와 자동화 결정 요건을 고정한다",()=>{const m=new Map(topic.content_entries.map(x=>[x.content_id,x]));assert.match(m.get("content.personal-data-rights-personal-data-breach-notice").one_line_answer_ko,/유출 항목.*시점.*경위.*비밀번호 변경/);assert.match(m.get("content.personal-data-rights-personal-data-access-request").one_line_answer_ko,/열람.*법정 기간.*제한·연기/);assert.match(m.get("content.personal-data-rights-personal-data-correction-and-deletion").one_line_answer_ko,/정정·삭제.*다른 법령.*삭제할 수 없습니다/);assert.match(m.get("content.personal-data-rights-stop-processing-and-withdraw-consent").one_line_answer_ko,/정지나 철회.*법률상 의무.*계약 이행/);assert.match(m.get("content.personal-data-rights-automated-decision-rights").one_line_answer_ko,/완전히 자동화.*권리·의무.*중대한 영향.*설명/)});

test("일반·배수·법정손해배상의 구조와 검증 판례 좌표를 고정한다",()=>{const e=topic.content_entries.find(x=>x.content_id==="content.personal-data-rights-data-breach-damages");assert.match(e.one_line_answer_ko,/제39조.*손해.*최대 5배.*제39조의2.*최대 300만원/);assert.match(e.caution_ko,/2023다311184.*구체적 손해 입증.*무손해 증명/);const p=topic.sources.find(x=>x.source_id==="src_prec_2023다311184_h2");assert.equal(p.case_number,"2023다311184");assert.equal(p.decision_date,"2025-12-04");assert.equal(p.official_url,"https://www.law.go.kr/LSW/precInfoP.do?precSeq=613235");assert.equal(p.source_snapshot_id,"snapshot:4a4c0fe767e6974d5dabb69e3b2e714560cdbfaf07585e079eab4ba1eff0857a")});

test("2026-07-22 기준 현행 개인정보 보호법 스냅샷만 사용한다",()=>{const expected=new Map([["personal_information_protection_ko_0015","snapshot:e654757c86ab53786b51ca739daabd20"],["personal_information_protection_ko_0016","snapshot:60c24aa82062c7f40ebc370a75000584"],["personal_information_protection_ko_0017","snapshot:2c4aab590dab12130645428c060f9db1"],["personal_information_protection_ko_0020","snapshot:457c1080d274839700bf17f54e26343c"],["personal_information_protection_ko_0026","snapshot:ae3b5f0d33cf20f598826d6003610940"],["personal_information_protection_ko_0034","snapshot:99022a4c8a0bb006c4f099e867cf79d2"],["personal_information_protection_ko_0035","snapshot:7921b39aee230b0365118999c6a387e6"],["personal_information_protection_ko_0036","snapshot:4e84c56cdbfb86b5d7b2f7add88336d9"],["personal_information_protection_ko_0037","snapshot:13bcf4ef716d0b2feb82ac2d82661bed"],["personal_information_protection_ko_0037_02","snapshot:7a6be397385dcb42ca232f30530ebe88"],["personal_information_protection_ko_0038","snapshot:b525ce8d0cc6abd2df22b45a97db4a64"],["personal_information_protection_ko_0039","snapshot:d631d6b6eaa752b34cd2f7af7326093d"],["personal_information_protection_ko_0039_02","snapshot:ab9d389cbad3c686c23be41504cda684"]]);const laws=topic.sources.filter(x=>!x.source_kind);assert.equal(laws.length,expected.size);for(const s of laws){assert.equal(s.source_snapshot_id,expected.get(s.source_id));assert.match(s.official_url,/^https:\/\/www\.law\.go\.kr\/%EB%B2%95%EB%A0%B9\//);assert.ok(s.official_url.endsWith(encodeURIComponent(s.article_no)))}});

test("기존 공개 콘텐츠로 연결되고 식별자가 충돌하지 않는다",async()=>{const ids=await otherContentIds();for(const e of topic.content_entries){assert.equal(ids.has(e.content_id),false);assert.ok(e.related_content_ids.length);for(const r of e.related_content_ids)assert.ok(ids.has(r),`${r} 없음`)}});

test("독립 인계본은 공유 출판 상태와 인적 표기를 변경하지 않는다",async()=>{const manifest=JSON.parse(await readFile(new URL("manifest.json",topicsDir),"utf8"));const integrated=JSON.stringify(manifest).includes(topicFileName);const current=JSON.parse(await readFile(new URL("../current/bundle.json",topicsDir),"utf8"));assert.equal(current.knowledge.topic_hubs.some(h=>h.hub_id===topic.topic_id),integrated);assert.equal(JSON.stringify(topic).includes("author"),false);assert.equal(JSON.stringify(topic).includes("reviewer"),false)});
